minor change

diff --git a/game/compile_and_run_mac b/game/compile_and_run_mac
--- a/game/compile_and_run_mac
+++ b/game/compile_and_run_mac
@@ -1,5 +1,10 @@
 #!/bin/bash
 cd "$(dirname "$0")"
 javac $(find ./* | grep .java) -d compiled
-cd compiled
-java game.Main
+
+if [ $? = 0 ]; then
+    cd compiled
+    java game.Main
+else
+    echo "error: compilation failed"
+fi
